export default [
    {
      title:"Física 1",
      subtitle:"Leis de Newton", 
      description:"Neste curso iremos aprender sobre as leis de Newton", 
      imageUrl:"https://static.todamateria.com.br/upload/le/is/leis-de-newton-og.jpg", 
      imageAlt:"Sir Newtin sentado embaixo de uma árvore escrevendo", 
      price:"R$27,90", 
      professor:"Lucas Albano", 
      estrelas:"4.5", 
      tempo:"5 horas",
    },
    {
      title:"Física 2",
      subtitle:"Leis de Newton", 
      description:"Neste curso iremos aprender sobre momento, oscilasções, hidroestática e hidrodinâmica", 
      imageUrl:"https://img.elo7.com.br/product/zoom/3413A48/adesivo-de-parede-63x190cm-arctic-monkeys-logo-ondu-r1385-adesivo-de-parede.jpg", 
      imageAlt:"Onda branca no fundo preto", 
      price:"R$27,90", 
      professor:"Lucas Albano", 
      estrelas:"4.4", 
      tempo:"6 horas",
    },
    {
      title:"Física 3",
      subtitle:"Eletromagnetismo", 
      description:"Neste curso iremos aprender sobre eletromagnetismo", 
      imageUrl:"https://registrodemarca.arenamarcas.com.br/wp-content/uploads/2020/05/Eletromagnetismo.jpg", 
      imageAlt:"Aquelas bolas de vidro que ligadas soltas miniraios com uma mão ao lado tocando nela", 
      price:"R$27,90", 
      professor:"Lucas Albano", 
      estrelas:"3.5", 
      tempo:"10 horas",
    },
    {
      title:"Cálculo 1",
      subtitle:"Leis de Newton", 
      description:"Neste curso iremos aprender limite, derivada e integral", 
      imageUrl:"https://www.cengage.com.br/wp-content/uploads/portadas/full/8522112584.jpg", 
      imageAlt:"Livro de cálculo 1 do James Stuart", 
      price:"R$15,90", 
      professor:"Lucas Albano", 
      estrelas:"4.2", 
      tempo:"8 horas",
    },
    {
      title:"Cálculo 2",
      subtitle:"Leis de Newton", 
      description:"Neste curso iremos aprender sobre momento, oscilasções, hidroestática e hidrodinâmica", 
      imageUrl:"https://image.isu.pub/130618185103-c04a239d5e5f6000ff79c8dd6f84404e/jpg/page_1.jpg", 
      imageAlt:"Livro de cálculo 2 do James Stuart", 
      price:"R$15,90", 
      professor:"Lucas Albano", 
      estrelas:"4.1", 
      tempo:"6 horas",
    },
    {
      title:"Cáculo 3",
      subtitle:"Integrais triplas", 
      description:"Neste curso iremos aprender sobre integrais triplas e outras formas de calcular volume", 
      imageUrl:"https://images-na.ssl-images-amazon.com/images/I/418w0By0FDL._SX344_BO1,204,203,200_.jpg", 
      imageAlt:"Livro de cálculo 3 do Guidorizzi", 
      price:"R$15,90", 
      professor:"Lucas Albano", 
      estrelas:"4.3", 
      tempo:"10 horas",
    },
    {
      title:"Curso de Café Especial Coado",
      subtitle:"Aprenda a fazer cafés especiais nos métodos: Hario V60, Chemex, Clever e Kalita", 
      description:"Neste curso você vai aprender sobre os métodos de extração de café coados, moagem e a importância da água", 
      imageUrl:"https://images.squarespace-cdn.com/content/545fa284e4b098772e50fd00/1571942506223-HK2RY3IX1O1WUJQ7Z1LA/Chemex+Pourover.jpg?format=1500w&content-type=image%2Fjpeg", 
      imageAlt:"Chemex", 
      price:"R$100,00", 
      professor:"Marye", 
      estrelas:"4.7", 
      tempo:"3 horas",
    },
    {
      title:"Pokémon Showdown - Básico",
      subtitle:"Entenda o básico para jogar Pokémon Showdown", 
      description:"Neste curso você vai aprender a jogar Pokémon Showdown , a relação entre os tipos de pokémon, terrenos, climas.", 
      imageUrl:"https://tinyurl.com/yyfv3vu9", 
      imageAlt:"Logo Pokémon Showdown", 
      price:"R$34,90", 
      professor:"Lucas Albano", 
      estrelas:"4.6", 
      tempo:"5 horas",
    },

    {
      title:"Como fazer massa folhada",
      subtitle:"Aprenda a fazer massa folhada do 0", 
      description:"Este curso explica de forma detalhada, simples e acessível como fazer massa folheada em casa! ", 
      imageUrl:"https://tinyurl.com/y5oj76gb", 
      imageAlt:"Foto de croissant cortado ao meio", 
      price:"R$ 35,00", 
      professor:"IV", 
      estrelas:"4.5", 
      tempo:"2 horas",
    },

    {
      title:"Curso de Lettering",
      subtitle:"Lettering para leigos se tornarem profissionais", 
      description:"Este curso ensina do básico ao avançado de lettering, não é preciso ter a letra bonita para fazer este curso. Neste curso você também vai aprender a fazer letterings em canecas, vidros e paredes!", 
      imageUrl:"https://http2.mlstatic.com/adesivo-decor-parede-uma-dose-caprichada-de-cafe-amor-e-fe-D_NQ_NP_745928-MLB31044497944_062019-F.jpg", 
      imageAlt:"Lettering na parede: uma dose caprichada de café, amor e fé", 
      price:"R$500,00", 
      professor:"Dani", 
      estrelas:"4,9", 
      tempo:"60 horas",
    },

    {
      title:"Kazoo para iniciantes",
      subtitle:"Como ser tao legal quanto o Kazoo kid", 
      description:"Vamos aprender a tocar Kazoo e ser tao legal quanto o kazoo kid", 
      imageUrl:"https://i.ytimg.com/vi/B1tL6rFsyAQ/hqdefault.jpg", 
      imageAlt:"Kazoo kid sendo legal", 
      price:"R$42,72", 
      professor:"Daniel Eiji Chiyo", 
      estrelas:"5,0", 
      tempo:"40 horas"
    },

    {
      title:"Reiki Básico",
      subtitle:"Reiki com Eiki", 
      description:"Ao final do curso você estará apto a reconhecer pontos vitais", 
      imageUrl:"https://guiadaalma.com.br/wp-content/uploads/2019/09/reiki-presencial-sao-paulo-bela-vista.jpg", 
      imageAlt:"Imagem de aplicação de Reiki", 
      price:"R$ 120,00", 
      professor:"Eiki", 
      estrelas:"4,3", 
      tempo:"6 horas",
    },

  ];